#!groovy

// Generated by IBM TransformationAdvisor
// Thu Nov 08 09:14:59 UTC 2018

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresortswar'
    mvnCommands = '--version'
    test='false'
}